"""
Snakefile for the splicing model
"""
workdir:
    "../../"
ROOT = "../.."
DATA = "data"

CLINVAR = "20180429"  # clinvar dowload date

# Which GPU to use
GPU = 1

from m_kipoi.config import list_models
MODELS = ["MaxEntScan", "HAL", "labranchor"]
MODELS_FULL = list_models(MODELS)

GTF_FILE = "data/raw/dataloader_files/shared/Homo_sapiens.GRCh37.75.filtered.gtf"
FASTA_FILE = "data/raw/dataloader_files/shared/hg19.fa"

rule all:
    input:
        # clinvar
        f"data/processed/splicing/clinvar/annotated_vcf/{CLINVAR}.filtered/modeling_df.tsv",
        f"data/raw/splicing/spidex/hg19_spidex.clinvar_{CLINVAR}.txt",
        # dbscSNV
        "data/processed/splicing/dbscSNV/modeling_df.tsv"

include:
    "download_annotation.smk"
include:
    "dbscSNV.smk"
include:
    "clinvar.smk"
include:
    "kipoi.smk"
